---
swagger: "2.0"
info:
  description: "Ulti send is provide service"
  version: "0.0.1"
  title: "Ulti Send"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ronaldsengkey@usahakreatif.co.id"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/ultiSend"
tags:
  - name: "api"
    description: "Permissions request for all access"
  - name: "source"
    description: "Source path"
schemes:
  - "https"
  - "http"
paths:
  /api/rate:
    get:
      tags:
        - "api"
      summary: "source request"
      description: "Global source access"
      operationId: "landingSource"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "service"
          in: "query"
          description: "service category (same day, Priority)"
          required: true
          type: "string"
          items:
            type: "string"
            default: "sameDay"
            enum:
              - "sameDay"
              - "priority"
          collectionFormat: "multi"
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"
      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

  /api/order:
    get:
      tags:
        - "api"
      summary: "get order request"
      description: "Order request from others app"
      operationId: "getOrder"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "service"
          in: "query"
          description: "service category (same day, Priority)"
          required: true
          type: "string"
          items:
            type: "string"
            default: "all"
            enum:
              - "sameDay"
              - "priority"
              - "all"
          collectionFormat: "multi"
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"

      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

    post:
      tags:
        - "api"
      summary: "order request"
      description: "Order request from"
      operationId: "postOrder"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "service"
          in: "query"
          description: "service category (same day, Priority)"
          required: true
          type: "string"
          items:
            type: "string"
            default: "sameDay"
            enum:
              - "sameDay"
              - "priority"
          collectionFormat: "multi"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/orderInquiry"

      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

  /api/order/assign:
    put:
      tags:
        - "api"
      summary: "order request"
      description: "Order request from"
      operationId: "assignOrderUpdate"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/assignOrderUpdateInquiry"
      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

    post:
      tags:
        - "api"
      summary: "order request"
      description: "Order request from"
      operationId: "assignOrderPost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/assignOrderInquiry"

      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

  /api/account:
    get:
      tags:
        - "api"
      summary: "account information"
      description: "get account information"
      operationId: "accountGet"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "category"
          in: "query"
          description: "request category"
          required: true
          type: "string"
          items:
            type: "string"
            default: "self"
            enum:
              - "self"
              - "driver"
              - "employee"
          collectionFormat: "multi"
        - name: "accountId"
          in: "query"
          description: "version api"
          required: false
          type: "integer"
          minimum: 1
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"

      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

    put:
      tags:
        - "api"
      summary: "order request"
      description: "Order request from"
      operationId: "accountUpdate"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/accountUpdateInquiry"
      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
      x-swagger-router-controller: "api"

    post:
      tags:
        - "api"
      summary: "order request"
      description: "Order request from"
      operationId: "accountPost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "v"
          in: "query"
          description: "version api"
          required: true
          type: "integer"
          default: 1
          minimum: 1
        - name: "token"
          in: "query"
          description: "user token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/accountPostInquiry"
      responses:
        "200":
          description: "Account post response"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: text description.
        "401":
          description: "Invalidunauthorize"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.
        "500":
          description: "Internal server error"
          schema:
            type: object
            properties:
              responseCode:
                type: integer
                description: code of response.
              responseText:
                type: string
                description: unauthorize.

      x-swagger-router-controller: "api"

definitions:
  accountPostInquiry:
    type: "object"
    properties:
      fullName:
        type: "string"
      userName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phoneCode:
        type: "string"
      phone:
        type: "string"
      image:
        type: "string"

  accountUpdateInquiry:
    type: "object"
    properties:
      name:
        type: "string"
      phone:
        type: "string"
      email:
        type: "string"
      image:
        type: "string"

  assignOrderUpdateInquiry:
    type: "object"
    properties:
      orderId:
        type: "string"
      driverId:
        type: "string"
      responseDate:
        type: "string"
      responseTime:
        type: "string"
      responseNotes:
        type: "string"
      image:
        type: "string"

  assignOrderInquiry:
    type: "object"
    properties:
      orderId:
        type: "string"
      driverId:
        type: "string"
      date:
        type: "string"
      time:
        type: "string"
      orderNotes:
        type: "string"

  orderInquiry:
    type: "object"
    properties:
      orderId:
        type: "string"
      merchantName:
        type: "string"
      merchantAddress:
        type: "string"
      merchantPhone:
        type: "string"
      receiverName:
        type: "string"
      receiverAddress:
        type: "string"
      receiverPhone:
        type: "string"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "application/json"
      message: "message"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
